pub mod alkanes_std_genesis_alkane_regtest_build;
pub mod alkanes_std_genesis_alkane_bellscoin_build;
pub mod alkanes_std_genesis_alkane_luckycoin_build;
pub mod alkanes_std_genesis_alkane_mainnet_build;
pub mod alkanes_std_genesis_alkane_fractal_build;
pub mod alkanes_std_genesis_alkane_dogecoin_build;
